services:
  douyin-local:
    build: .
    container_name: douyin-local
    ports:
      - "7077:7077"
    volumes:
      - "/vol00/WDC WD10SDZW-11UMGS0/truvaze_videos:/videos:ro"
    environment:
      - VIDEO_DIR=/videos
    restart: always
